[package]
name = "simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
upstair_type.workspace = true
crossbeam.workspace = true
priority-queue = "1.3.2"
tracing.workspace = true
