[package]
name = "binance_data_download"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
indicatif.workspace = true
reqwest = "0.12.4"
tokio = { version = "1.37.0", features = ["full"] }
anyhow.workspace = true
zip.workspace = true
polars.workspace = true
